spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/semogong
    username: talk-with
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'dlwogns1205@gmail.com'
    password: 'mrah qxxf okfz fwjf'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cors:
    allowed-origins:
      - http://localhost:3000 # 클라이언트 도메인 설정
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS # 필요한 HTTP 메서드 설정
    allow-credentials: true # 쿠키 허용 설정

logging.level:
  org.hibernate.SQL: debug




# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6